/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AdminHeader: typeof import('./src/components/AdminHeader.vue')['default']
    AdminLayout: typeof import('./src/components/AdminLayout.vue')['default']
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    AdminTabs: typeof import('./src/components/AdminTabs.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BellOutlined: typeof import('@ant-design/icons-vue')['BellOutlined']
    CloseCircleOutlined: typeof import('@ant-design/icons-vue')['CloseCircleOutlined']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    FullscreenExitOutlined: typeof import('@ant-design/icons-vue')['FullscreenExitOutlined']
    FullscreenOutlined: typeof import('@ant-design/icons-vue')['FullscreenOutlined']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LogoutOutlined: typeof import('@ant-design/icons-vue')['LogoutOutlined']
    MoonOutlined: typeof import('@ant-design/icons-vue')['MoonOutlined']
    QuestionCircleOutlined: typeof import('@ant-design/icons-vue')['QuestionCircleOutlined']
    ReloadOutlined: typeof import('@ant-design/icons-vue')['ReloadOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    SunFilled: typeof import('@ant-design/icons-vue')['SunFilled']
    SunOutlined: typeof import('@ant-design/icons-vue')['SunOutlined']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
